name: Run Command w/ Akamai Key

on:
  workflow_dispatch:
    inputs:
      customCommand:
        description: 'command to run with akamai key'
        required: true


jobs:
  run-akamai-command:
    name: Build & Run Command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: |
          npm ci
          npm rebuild && npm run prepare --if-present
      - run: ${{ github.event.inputs.customCommand }}
        env:
          NODE_ENV: 'production'
